
package view;


public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        mnConsulta = new javax.swing.JMenuItem();
        mnExtrato = new javax.swing.JMenuItem();
        mnDepositar = new javax.swing.JMenuItem();
        mnSacar = new javax.swing.JMenuItem();
        mnComprar = new javax.swing.JMenuItem();
        mnVender = new javax.swing.JMenuItem();
        mnAtualiza = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setText("Cadastrar");

        mnConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnConsulta.setText("Consultar saldo");
        mnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultaActionPerformed(evt);
            }
        });
        Menu.add(mnConsulta);

        mnExtrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnExtrato.setText("Consultar extrato");
        mnExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExtratoActionPerformed(evt);
            }
        });
        Menu.add(mnExtrato);

        mnDepositar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnDepositar.setText("Depositar");
        mnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepositarActionPerformed(evt);
            }
        });
        Menu.add(mnDepositar);

        mnSacar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnSacar.setText("Sacar");
        mnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSacarActionPerformed(evt);
            }
        });
        Menu.add(mnSacar);

        mnComprar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnComprar.setText("Comprar cripto");
        mnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnComprarActionPerformed(evt);
            }
        });
        Menu.add(mnComprar);

        mnVender.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnVender.setText("Vender cripto");
        mnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVenderActionPerformed(evt);
            }
        });
        Menu.add(mnVender);

        mnAtualiza.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnAtualiza.setText("Atualizar cotação");
        mnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizaActionPerformed(evt);
            }
        });
        Menu.add(mnAtualiza);

        mnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        Menu.add(mnSair);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultaActionPerformed
        Consultar consultar = new Consultar();
        consultar.setVisible(true);
    }//GEN-LAST:event_mnConsultaActionPerformed

    private void mnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepositarActionPerformed
        Depositar depositar = new Depositar();
        depositar.setVisible(true);
    }//GEN-LAST:event_mnDepositarActionPerformed

    private void mnExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExtratoActionPerformed
        Extrato extrato = new Extrato();
        extrato.setVisible(true);
    }//GEN-LAST:event_mnExtratoActionPerformed

    private void mnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSacarActionPerformed
        Sacar sacar = new Sacar();
        sacar.setVisible(true);
    }//GEN-LAST:event_mnSacarActionPerformed

    private void mnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnComprarActionPerformed
        Comprar comprar = new Comprar();
        comprar.setVisible(true);
    }//GEN-LAST:event_mnComprarActionPerformed

    private void mnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVenderActionPerformed
        Vender vender = new Vender();
        vender.setVisible(true);
    }//GEN-LAST:event_mnVenderActionPerformed

    private void mnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizaActionPerformed
        Atualizar atualizar = new Atualizar();
        atualizar.setVisible(true);
    }//GEN-LAST:event_mnAtualizaActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAtualiza;
    private javax.swing.JMenuItem mnComprar;
    private javax.swing.JMenuItem mnConsulta;
    private javax.swing.JMenuItem mnDepositar;
    private javax.swing.JMenuItem mnExtrato;
    private javax.swing.JMenuItem mnSacar;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnVender;
    // End of variables declaration//GEN-END:variables
}
